sonar.projectKey=orders
sonar.projectName=orders-service
sonar.sources=.
sonar.language=go
sonar.sourceEncoding=UTF-8

# Excluir archivos innecesarios
sonar.exclusions=**/vendor/**,**/tests/**,**/*_test.go

# Ruta del archivo de cobertura generado por go test
sonar.go.coverage.reportPaths=coverage.out
